export enum TournamentFormat {
  SINGLE_ELIMINATION = 'SINGLE_ELIMINATION',
  DOUBLE_ELIMINATION = 'DOUBLE_ELIMINATION',
  ROUND_ROBIN = 'ROUND_ROBIN',
  SWISS_SYSTEM = 'SWISS_SYSTEM',
}

export enum TournamentStatus {
  DRAFT = 'DRAFT',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ParticipantStatus {
  REGISTERED = 'REGISTERED',
  CONFIRMED = 'CONFIRMED',
  ACTIVE = 'ACTIVE',
  ELIMINATED = 'ELIMINATED',
  WITHDRAWN = 'WITHDRAWN',
  DISQUALIFIED = 'DISQUALIFIED',
}

export enum MatchStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum BracketPosition {
  WINNERS = 'WINNERS',
  LOSERS = 'LOSERS',
  FINALS = 'FINALS',
}

export enum TournamentEventType {
  TOURNAMENT_CREATED = 'TOURNAMENT_CREATED',
  TOURNAMENT_UPDATED = 'TOURNAMENT_UPDATED',
  TOURNAMENT_DELETED = 'TOURNAMENT_DELETED',
  REGISTRATION_OPENED = 'REGISTRATION_OPENED',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  PARTICIPANT_REGISTERED = 'PARTICIPANT_REGISTERED',
  PARTICIPANT_CONFIRMED = 'PARTICIPANT_CONFIRMED',
  PARTICIPANT_REMOVED = 'PARTICIPANT_REMOVED',
  TOURNAMENT_STARTED = 'TOURNAMENT_STARTED',
  MATCH_SCHEDULED = 'MATCH_SCHEDULED',
  MATCH_STARTED = 'MATCH_STARTED',
  MATCH_COMPLETED = 'MATCH_COMPLETED',
  PARTICIPANT_ELIMINATED = 'PARTICIPANT_ELIMINATED',
  ROUND_COMPLETED = 'ROUND_COMPLETED',
  TOURNAMENT_COMPLETED = 'TOURNAMENT_COMPLETED',
  PRIZE_DISTRIBUTED = 'PRIZE_DISTRIBUTED',
}

export enum PrizeType {
  CASH = 'CASH',
  ITEM = 'ITEM',
  POINTS = 'POINTS',
  TROPHY = 'TROPHY',
  TITLE = 'TITLE',
}
